### PR TITLE
Enhancement to render markdown files like nbconvert

### PR DESCRIPTION
**Pull request by troppens**
PHP and CSS code to render a GitHub markdown file like nbconvert. This addresses feature request #5.
The below web page is created with the new shortcut.

image

### CODE REVIEW

**Comment by nilsnolde** [comment]
Thanks Ulf! 

Can you request my review? There's a few things I'd like to change (more semantic, nothing big) and that'd make it easier.

Will also add a Contributor section after PR, no problem.

**Comment by troppens** [comment]
This is my first pull request ever and I have not found the button to request a review. I will try it later after reading the docs.

**Comment by troppens** [comment]
I cannot request a review as describe here:
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/requesting-a-pull-request-review

I do not see any reviewers in the right sidebar.

**Comment by nilsnolde** [comment]
No worries Ulf, wasn't aware of that either. Let's just do it in here then.

I just tried it and it works fine. Looks like the original:)

What I'd like to change is:

- rename shortcode to `nbconvert_github`
- maybe it's best if you add a Contributors section in the README, like
```
<h2>Contributors</h2>
- Name: email
```
- Since this shortcode should be mutually exclusive with `md_github` and `checkout_github`, please mention that in the README
- The README should say:

> It features **4** shortcodes:
...
> `[mdnotebook_github token=YourToken url=Github URL]` : Displays GitHub markdown file similar to nbconvert.

And include a link to Andy's repo in `nbconvert`.

After that's done, I can publish on WordPress repo.

**Comment by troppens** [comment]
I believe that the 'nb' in 'nbconvert' stands for 'Jupyter Notebook'.

Therefore I would suggest rename the shortcode to 'mdconvert_github' to
- align with your naming scheme
- have a reference to nbconvert
- have a reference to markdown instead of a reference to Jupyter notebooks

**Comment by nilsnolde** [comment]
But `mdconvert` doesn't say anything. Agreed though, `nbconvert` is not much better either. Then maybe `md_dashedbox_github` to at least hint at what it's doing. My "naming scheme" is not to be taken serious;)

**Comment by troppens** [comment]
Sounds good. I will make and test the changes later.

**Comment by troppens** [comment]
@nilsnolde - I believe that I now have addressed all review comments.

Though I noticed on other minor issues. Look at the screenshot at the beginning of this pull request. Each item begins with '>>', but it should be a filled circle'.

**Comment by troppens** [comment]
So, I see the '>>' also with your original shortcode. So it seems to be related to my Wordpress theme.

@nilsnolde - I think this pull request is ready to merge.

**Comment by nilsnolde** [comment]
Jup looks good, thanks.

**Pull request merged**
